
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbtpoccluster'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtpocsqlwhs'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:  
  dbtpoccluster:
    # Config indicated by + and applies to all files under models/example/
    stage:
      +schema: "{{ 'stage' if target.name == 'dev' else 'prod_stage' }}"
      +location_root: "{{ 'abfss://jason@stdatalzdevlake.dfs.core.windows.net/stage' if target.name == 'dev' else 'abfss://jason@stdatalzdevlake.dfs.core.windows.net/prod_stage'}}"
    bronze:
      +schema: "{{ 'bronze' if target.name == 'dev' else 'prod_bronze' }}"
      +location_root: abfss://jason@stdatalzdevlake.dfs.core.windows.net/bronze
    silver:
      +file_format: delta
      +schema: "{{ 'silver' if target.name == 'dev' else 'prod_silver' }} "
      +location_root: "{{ 'abfss://jason@stdatalzdevlake.dfs.core.windows.net/silver' if target.name == 'dev' else 'abfss://jason@stdatalzdevlake.dfs.core.windows.net/prod_silver'}}"
    gold:
      +file_format: delta
      +schema: gold
      +location_root: abfss://jason@stdatalzdevlake.dfs.core.windows.net/gold

vars:
  somevar: 2